### ISSUE TITLE
GCC with Go support?

### ISSUE THREAD

**Issue by ghost** [mfe-/ReadyNASDuoSparc#3]
I saw on the Netgear forums that you were trying to compile GCC 7.1 with Go support.  Did you ever have any luck with that?
I am going crazy trying to compile newer GCC on this thing.

**Comment by mfe-** [comment]
@os144046 Since the readynas duo doesnt support Thread Local Storage (and go relies on that feature), it looks like there is no way to run go on the Readynas Duo. For more details check: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90645

Edit: I managed to compile gcc 4.6 and gcc7.1 on the readynas duo. For example the git binary which is contained in this repository was compiled using gcc4.6.

**Comment by ghost** [comment]
Ah ok.  I needed Go, but I will use something else.  Thanks!

**Comment by mfe-** [comment]
@os144046 I think the best chance for getting software running on the readynas duo is if the software is build with C or C++ using the gnu/gcc build toolchain. If the software is using an old C/C++ version you can try compile it with gcc4.6 otherwise try gcc7.1 from this repo.
